/* TABLAS */

CREATE TABLE SEMESTRE(
Id INT NOT NULL,
Periodo INT NOT NULL,
Año INT NOT NULL
);

CREATE TABLE GRUPO(
Id INT NOT NULL,
Id_Curso INT NOT NULL
);

CREATE TABLE ROL(
Id INT NOT NULL,
Nombre VARCHAR(20) NOT NULL
);

CREATE TABLE USUARIO(
Id INT NOT NULL,
Id_Rol INT NOT NULL
);

CREATE TABLE PERTENECE_USUARIO_GRUPO(
Id_Curso INT NOT NULL,
Id_Usuario INT NOT NULL
);

CREATE TABLE RUBRO(
Id INT NOT NULL,
Nombre VARCHAR(20) NOT NULL,
Porcentaje INT DEFAULT 0,
Id_Elemento INT
);

CREATE TABLE USUARIO_ADMINISTRA_RUBRO(
Id_Rubro INT NOT NULL,
Id_Usuario INT  NOT NULL
);







CREATE TABLE EVALUACION(
Id INT NOT NULL,
Id_Rubro INT NOT NULL,
Grupal INT,
Fecha_Entrega DATE NOT NULL,
Observaciones VARCHAR(200),
Especificacion VARBINARY,
Porcentaje INT
);

CREATE TABLE USUARIO_ASIGNA_EVALUACION(
Id_Usuario INT NOT NULL,
Id_Evaluacion INT NOT NULL
);


CREATE TABLE NOTICIA
(
Id INT NOT NULL,
Titulo VARCHAR(50),
Mensaje VARCHAR(200),
Fecha DATE,
Autor INT NOT NULL
);

CREATE TABLE CURSO
(
Id INT NOT NULL,
Nombre VARCHAR(20),
Carrera VARCHAR(20),
Creditos INT,
Semestre INT NOT NULL
);

CREATE TABLE NOTICIA_DE_CURSO
(
Id_Noticia INT NOT NULL,
Id_Curso INT NOT NULL
);









CREATE TABLE ELEMENTO
(
Id INT NOT NULL,
Tipo INT NOT NULL,
Visualizar INT,
Tamaño VARCHAR(10),
Archivo VARBINARY,
Nombre VARCHAR(20),
Fecha_Creacion DATE
)

CREATE TABLE TIPO
(
Id INT NOT NULL,
Nombre VARCHAR(20)
)

CREATE TABLE ELEMENTO_CONTIENE_ELEMENTO
(
Id_Elemento INT NOT NULL,
Id_ElementoC INT NOT NULL
)

CREATE TABLE USUARIO_CREA_ELEMENTO
(
Id_Usuario INT NOT NULL,
Id_Elemento INT NOT NULL
)

CREATE TABLE ENTREGABLE
(
Id INT NOT NULL,
Id_Evaluacion INT NOT NULL,
Nombre VARCHAR(20),
Archivo VARBINARY,
Observaciones VARCHAR(200),
Nota INT,
Nota_Publica INT
)

CREATE TABLE USUARIO_SUBE_ENTREGABLE
(
Id_Usuario INT NOT NULL,
Id_Entregable INT NOT NULL
)



/* LLAVES PRIMARIAS */

ALTER TABLE SEMESTRE
ADD CONSTRAINT SEMESTRE_PK PRIMARY KEY(Id);

ALTER TABLE PERTENECE_USUARIO_GRUPO
ADD CONSTRAINT PERTENECE_USUARIO_GRUPO_PK PRIMARY KEY(Id_Curso,Id_Usuario);

ALTER TABLE USUARIO_ADMINISTRA_RUBRO
ADD CONSTRAINT USUARIO_ADMINISTRA_RUBRO_PK PRIMARY KEY(Id_Rubro,Id_Usuario);

ALTER TABLE USUARIO_ASIGNA_EVALUACION
ADD CONSTRAINT USUARIO_ASIGNA_EVALUACION_PK PRIMARY KEY(Id_Usuario,Id_Evaluacion);

ALTER TABLE USUARIO
ADD CONSTRAINT USUARIO_PK PRIMARY KEY(Id);

ALTER TABLE GRUPO
ADD CONSTRAINT GRUPO_PK PRIMARY KEY(Id);

ALTER TABLE ROL
ADD CONSTRAINT ROL_PK PRIMARY KEY(Id);

ALTER TABLE RUBRO
ADD CONSTRAINT RUBRO_PK PRIMARY KEY(Id);

ALTER TABLE EVALUACION
ADD CONSTRAINT EVALUACION_PK PRIMARY KEY(Id);

ALTER TABLE ELEMENTO
ADD CONSTRAINT ELEMENTO_PK PRIMARY KEY(Id);

ALTER TABLE NOTICIA
ADD CONSTRAINT NOTICIA_PK PRIMARY KEY(Id);

ALTER TABLE CURSO
ADD CONSTRAINT CURSO_PK PRIMARY KEY(Id);

ALTER TABLE NOTICIA_DE_CURSO
ADD CONSTRAINT NOTICIA_DE_CURSO_PK PRIMARY KEY(Id_Noticia,Id_Curso);

ALTER TABLE TIPO
ADD CONSTRAINT TIPO_PK PRIMARY KEY(Id);

ALTER TABLE ELEMENTO_CONTIENE_ELEMENTO
ADD CONSTRAINT ELEMENTO_CONTIENE_PK PRIMARY KEY(Id_Elemento,Id_ElementoC);

ALTER TABLE USUARIO_CREA_ELEMENTO
ADD CONSTRAINT USUARIO_CREA_ELEMENTO_PK PRIMARY KEY(Id_Usuario,Id_Elemento);

ALTER TABLE ENTREGABLE
ADD CONSTRAINT ENTREGABLE_PK PRIMARY KEY(Id);

ALTER TABLE USUARIO_SUBE_ENTREGABLE
ADD CONSTRAINT USUARIO_SUBE_ENTREGABLE_PK PRIMARY KEY(Id_Usuario,Id_Entregable);

/* LLAVES FORANEAS */ 

ALTER TABLE GRUPO
ADD CONSTRAINT GRUPO_FK FOREIGN KEY(Id_Curso)
REFERENCES CURSO(Id);

ALTER TABLE USUARIO
ADD CONSTRAINT USUARIO_FK FOREIGN KEY(Id_Rol)
REFERENCES ROL(Id);

ALTER TABLE PERTENECE_USUARIO_GRUPO
ADD CONSTRAINT PERTENECE_USUARIO_GRUPO_CURSO_FK FOREIGN KEY(Id_Curso)
REFERENCES CURSO(Id);

ALTER TABLE PERTENECE_USUARIO_GRUPO
ADD CONSTRAINT PERTENECE_USUARIO_GRUPO_USUARIO_FK FOREIGN KEY(Id_Usuario)
REFERENCES USUARIO(Id);

ALTER TABLE USUARIO_ADMINISTRA_RUBRO
ADD CONSTRAINT USUARIO_ADMINISTRA_RUBRO_RUBRO_FK FOREIGN KEY(Id_Rubro)
REFERENCES RUBRO(Id);

ALTER TABLE USUARIO_ADMINISTRA_RUBRO
ADD CONSTRAINT USUARIO_ADMINISTRA_RUBRO_USUARIO_FK FOREIGN KEY(Id_Usuario)
REFERENCES USUARIO(Id);

ALTER TABLE EVALUACION
ADD CONSTRAINT EVALUACION_RUBRO_FK FOREIGN KEY(Id_Rubro)
REFERENCES RUBRO(Id);

ALTER TABLE USUARIO_ASIGNA_EVALUACION
ADD CONSTRAINT USUARIO_ASIGNA_EVALUACION_USUARIO_FK FOREIGN KEY(Id_Usuario)
REFERENCES USUARIO(Id);

ALTER TABLE USUARIO_ASIGNA_EVALUACION
ADD CONSTRAINT USUARIO_ASIGNA_EVALUACION_EVALUACION_FK FOREIGN KEY(Id_Evaluacion)
REFERENCES EVALUACION(Id);

ALTER TABLE NOTICIA
ADD CONSTRAINT NOTICIA_USUARIO_FK FOREIGN KEY(Autor)
REFERENCES USUARIO(Id);

ALTER TABLE CURSO
ADD CONSTRAINT CURSO_SEMESTRE_FK FOREIGN KEY(Semestre)
REFERENCES SEMESTRE(Id);

ALTER TABLE NOTICIA_DE_CURSO
ADD CONSTRAINT NOTICIA_DE_CURSO_FK FOREIGN KEY(Id_Noticia)
REFERENCES  NOTICIA(Id);

ALTER TABLE NOTICIA_DE_CURSO
ADD CONSTRAINT CURSO_DE_NOTICIA_FK FOREIGN KEY(Id_Curso)
REFERENCES  CURSO(Id);

ALTER TABLE ELEMENTO
ADD CONSTRAINT ELEMENTO_TIPO_FK FOREIGN KEY(Tipo)
REFERENCES TIPO(Id);

ALTER TABLE ELEMENTO_CONTIENE_ELEMENTO
ADD CONSTRAINT ELEMENTO_CONTIENE_TIPO_FK FOREIGN KEY(Id_Elemento)
REFERENCES ELEMENTO(Id);

ALTER TABLE ELEMENTO_CONTIENE_ELEMENTO
ADD CONSTRAINT CONTIENE_ELEMENTO_TIPO_FK FOREIGN KEY(Id_ElementoC)
REFERENCES ELEMENTO(Id);

ALTER TABLE USUARIO_CREA_ELEMENTO
ADD CONSTRAINT USUARIO_CREA_ELEMENTO_FK FOREIGN KEY(Id_Usuario)
REFERENCES Usuario(Id);

ALTER TABLE USUARIO_CREA_ELEMENTO
ADD CONSTRAINT ELEMENTO_CREA_USUARIO_FK FOREIGN KEY(Id_Elemento)
REFERENCES ELEMENTO(Id);

ALTER TABLE ENTREGABLE
ADD CONSTRAINT ENTREGABLE_EVALUACION_FK FOREIGN KEY(Id_Evaluacion)
REFERENCES Evaluacion(Id);

ALTER TABLE USUARIO_SUBE_ENTREGABLE
ADD CONSTRAINT USUARIO_SUBE_ENTREGABLE_FK FOREIGN KEY(Id_Usuario)
REFERENCES USUARIO(Id);

ALTER TABLE USUARIO_SUBE_ENTREGABLE
ADD CONSTRAINT ENTREGABLE_SUBE_USUARIO_FK FOREIGN KEY(Id_Entregable)
REFERENCES ENTREGABLE(Id);

/*
-- Primero desabilitar la integridad referencial
 EXEC sp_MSForEachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'
 GO
EXEC sp_MSforeachtable @command1 = "DROP TABLE ?"
-- Ahora volver a habilitar la integridad referencial
 EXEC sp_MSForEachTable 'ALTER TABLE ? CHECK CONSTRAINT ALL'
 GO
 */